# Generated by Django 5.0.7 on 2024-07-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_importtant_todo_important_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='datecompleted',
            new_name='date_completed',
        ),
    ]
