name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage pytest-django

    - name: Set up the database
      env:
        DJANGO_SETTINGS_MODULE: todowo.settings
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_NAME: github_actions
        DB_HOST: localhost
        DB_PORT: 5432
      run: |
        python manage.py migrate

    - name: Run tests with coverage
      run: |
        coverage run --source=todowo/ -m pytest
        coverage report
      env:
        DJANGO_SETTINGS_MODULE: todowo.settings
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_NAME: github_actions
        DB_HOST: localhost
        DB_PORT: 5432
